Create endpoint feedback
huggingface/hf-endpoints-documentation pull request #11
Opened 2022-10-18 22:06 UTC by stevhliu

Similar to my other PR, I think it'd be better to use a regular list instead of formatting them as section headers. The other suggestion is to combine the advanced configuration with the create an endpoint doc. I think it'd be better to keep all the setup information together and not send the user to a different page if they want to learn more about the configuration options during setup.

2022-10-18 22:09 UTC, HuggingFaceDocBuilder commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/inference-endpoints/pr_11). All of your documentation changes will be reflected on that endpoint.

2022-11-21 17:34 UTC, stevhliu commented
Thanks! Pinging @philschmid for a last look/merge too :)

2022-11-21 17:36 UTC, philschmid requested changes
We should keept the `###` headers in there to directly link to it. 
And IMO the Advanced Configuration should stay separate since those things will be in the future extended, with new instances types and other features which require more documentation.

2022-11-21 17:50 UTC, philschmid approved these changes

2022-11-21 17:56 UTC, merged